### PR TITLE
Merge in Anders' 1.0.5.3 from NSIS Wiki

### PR DESCRIPTION
**Pull request by Nutzzz**
It updates /tostackconv to support UTF-8 and UTF-16LE BOM sniffing and conversion

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/2)

### CODE REVIEW

**Review by Nutzzz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/2)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[Contrib/Inetc/inetc.cpp, line 191 at r2](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/2#-LNltZ4A1xf5_0xaC9tN:-LNltZ4A1xf5_0xaC9tO:b-lha8dc) ([raw file](https://github.com/digitalmediaserver/nsis-inetc-plugin/blob/d4856b58489c4989316ba073d9f08c801450dd6c/Contrib/Inetc/inetc.cpp#L191)):*
> ```cpp
> #define MY_WEAKSECURITY_CERT_FLAGS INTERNET_FLAG_IGNORE_CERT_CN_INVALID | INTERNET_FLAG_IGNORE_CERT_DATE_INVALID
> #define MY_REDIR_FLAGS INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTP | INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTPS
> #define MY_HTTPS_FLAGS (MY_REDIR_FLAGS | INTERNET_FLAG_SECURE)
> ```

I may have screwed up what you were doing with 1.0.5.5 when I merged this part.  I'm not sure why Anders did it this way.

**Comment by Nadahar** [comment]
It seems like this merging has gone quite wrong, you have unresolved conflicts in the commits and you haven't started with an updated master.

It might be easier if you show me the commit(s) with Anders' changes.

**Review by Nutzzz — COMMENTED** [review]
Sorry, my starting point was conflicted, but the end result should be correct.  Anyway, there aren't that many changes, feel free to merge it yourself from the wiki source.

> *[Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/2#-:-LNmA4140-YkmNIZw2n1:b-2a25ym)* status: 0 of 2 files reviewed, 1 unresolved discussion

**Comment by Nadahar** [comment]
@Nutzzz I found it easier to pick the changes from the wiki ZIP. I've added them as a new commit and made a new release.

**Pull request closed without merging**
