### PR TITLE
Fix MulDiv arguments for files > 2 GB; make unicode the default

### PR DESCRIPTION
**Pull request by pjpuchyr**
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/8)

### CODE REVIEW

**Comment by Nadahar** [comment]
@pjpuchyr Thank you :+1: Please give me a little bit of time to dust off my old build system and see that it still builds OK. I will have to revert some of the changes to the project file, as it is a goal that it should still build a valid binary for older systems like Windows XP.

**Comment by Nadahar** [comment]
I had to remove your changes to the project to make it build with VS 2010. The "change to unicode" wasn't necessary either, the project have 4 "configurations", Win32 ANSI and Unicode, x64 ANSI and Unicode. I always build all 4.

**Review by Nadahar — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-inetc-plugin/8#-:-MzGDLvv5QhRppW4RvL_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pjpuchyr)

**Comment by Nadahar** [comment]
@pjpuchyr Again, thank you for the fix :+1:

**Comment by pjpuchyr** [comment]
No problem.

One more adjustment.  I chose the point at which the cnt and fs was reduced
(2^31/100) to ensure that cnt*100 < 2^31, just in case the multiplication
in MulDiv was done before the division.  Now I've realized that the second
MulDiv possibly involved cnt*PB_RANGE, with PB_RANGE=400.  It's probably
best to keep it simple and test if fs > 2^31/1024 (=2^21=2097152).

Thanks for putting INetC out there; it saved my bacon on an installer
project I'm working on.  I know nothing about the intricacies of internet
file transfer, so I really appreciated you doing that, including putting up
the VS project file.

Regards,
Peter
***************************************************
Peter J. Puchyr, M.Sc.
SpaceTime Simulation Corp

**Pull request merged**
